### ISSUE TITLE
Add "Create New Default Routing Rule"

### ISSUE THREAD

**Issue by derekritchison** [scrthq/PSGSuite#171] opened 2019-04-03 20:45 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by derekritchison** [comment] 2019-04-03 20:46
When we terminate a former employee we temporarily create a default routing rule that "changes the envelope recipient" from the former employee to their manager. Would be nice if I could automate this with PowerShell.

**Comment by scrthq** [comment] 2019-04-03 20:50
hey @derekritchison - I want to say that this isn't doable via API currently, but I'll confirm! If you happen to have a link to any of Google's API documentation that handles this already, that would help me expedite this =]

**Comment by scrthq** [comment] 2019-04-03 20:53
The [Admin Settings API](https://developers.google.com/admin-sdk/admin-settings/) may do it, but it's also been flagged for deprecation and I'm not aware of a replacement for it yet

**Comment by derekritchison** [comment] 2019-04-03 20:55
Thanks for the incredibly quick response. Gonna read up on that API even though it's deprecated, because I'm kinda curious.

**Comment by scrthq** [comment] 2019-04-03 20:55
Other links:
https://gsuiteupdates.googleblog.com/2017/10/shutdown-of-gdata-admin-settings-api.html

https://gsuiteupdates.googleblog.com/2018/10/gdata-admin-settings-api-shutdown-update.html

Note from that last one:

![image](https://user-images.githubusercontent.com/12724445/55512500-f0320000-5628-11e9-830f-6ebb05b353af.png)

**Comment by scrthq** [comment] 2019-04-03 20:57
I'll work on adding support for the current API since your desired endpoint is still up until they have a replacement for it, at which time I'll work in the replacement similar to what I did for the Gmail Inbox Delegation endpoints once they were rolled into the Gmail API

**Comment by derekritchison** [comment] 2019-04-03 21:00
This is what we currently configure, manually, on Google Admin.

<img width="392" alt="routing" src="https://user-images.githubusercontent.com/28872338/55512781-d092db80-5618-11e9-986c-a8c6f78d8f1c.PNG">

**Comment by scrthq** [comment] 2019-04-03 21:03
Gotcha! So, I want to say that setting up compliance rules like that are not manageable from API calls. The Admin Settings API would be able to manage your overall email route / gateway, but not those types of rules as far as I'm aware.

**Comment by scrthq** [comment] 2019-04-03 21:13
Yeah, pretty positive that any settings at that level are not configurable via API. What about adding in a filter to forward to the replacement recipient instead? I know it's not as direct as setting up a compliance rule as noted, but that would absolutely be configurable via existing commands in PSGSuite if desired.

**Comment by derekritchison** [comment] 2019-04-03 21:24
I believe that would require the former employee's inbox to remain active.

**Comment by scrthq** [comment] 2019-04-03 21:26
It would indeed, unfortunately. At least the Gmail service. With your offboarding process, are you completely deleting the user, flipping them over to a Vault license, or something else?

**Comment by derekritchison** [comment] 2019-04-04 03:07
Completely deleting, after doing a full .mbox export.

**Comment by scrthq** [comment] 2019-04-04 20:40
@derekritchison - Got it! Alright, yeah, I believe I'm a little stuck here then based on lack of public API from Google's side for that specific functionality.

Were you interested in any of the remaining Admin Settings API functionality being added? I will get them added as-is if desired, otherwise I'm going to close this out and revisit once Google adds the functionality to the Admin SDK

**Comment by derekritchison** [comment] 2019-04-04 20:45
Understood! Would definitely be a nice feature when it's available as it would streamline our offboarding process even more. Feel free to close the thread!

That said, maybe this is off topic but I'm curious about the "Add-GSGmailFilter" command. What I'm trying to do is create a filter based on one criteria --- if a certain e-mail address appears in the "To" field. Far as I understand the command should look like this:

Add-GSGmailFilter -User <my address> -To <another user's address> -AddLabelIDs <whatever label I'm using for this filter>

Am I missing something, or just misunderstanding the purpose of this command entirely?

**Comment by scrthq** [comment] 2019-04-04 20:57
No worries, that should be accurate! Are you getting an error or unexpected behavior or....?

**Comment by scrthq** [comment] 2019-04-04 20:58
Worth noting that if it's a non-standard LabelID (basically any label that you created yourself), you will need to pull the actual label ID first using `Get-GSGmailLabel`

**Comment by derekritchison** [comment] 2019-04-04 21:30
I see, so if I create a label for another user by running...

New-GSGmailLabel -User <user@domain.com> -Name <Label Name>

...I then have to somehow grab the unique "LabelID" before running my next step, which would be setting up that new filter?

**Comment by scrthq** [comment] 2019-04-04 21:40
It'll return the newly created label, so if you capture that in a variable, you can easily access the ID without querying the label list again:

![image](https://user-images.githubusercontent.com/12724445/55590327-2d18f800-56f8-11e9-838a-ed9c37987ea4.png)

You'll get a conflict if the label name already exists:

![image](https://user-images.githubusercontent.com/12724445/55590370-4c178a00-56f8-11e9-9115-bb0ac800b85b.png)

**Comment by scrthq** [comment] 2019-04-04 21:43
This is the error you'll see if the label ID you're trying to access doesn't exist:

![image](https://user-images.githubusercontent.com/12724445/55590463-97319d00-56f8-11e9-9a92-d02974198c65.png)

Compared to a successful run where we use the actual labelID:

![image](https://user-images.githubusercontent.com/12724445/55590506-b8928900-56f8-11e9-9777-94dafa620499.png)

**Comment by derekritchison** [comment] 2019-04-04 21:44
Great. Thanks! Been very helpful!

**Comment by scrthq** [comment] 2019-04-05 02:54
Happy to hear!! Let me know if you have any other questions!! Cheers!

**Closed by scrthq** 2019-04-05 02:54 UTC
Labels: enhancement
