### ISSUE TITLE
'Get-GSGroupMember -Identity mygroup' - DeliverySettings are not populated on the group member objects.

### ISSUE THREAD

**Issue by n-searle** [scrthq/PSGSuite#124] opened 2018-11-28 20:36 UTC
Hi Nate,

When returning all group members with:
`Get-GSGroupMember -Identity mygroup`

DeliverySettings is not populated on the group member objects.

When returning a specific member with:
`Get-GSGroupMember -Identity mygroup -member neil.searle`

DeliverySettings is populated.

**Expected behavior**
DeliverySettings to be populated with either get-gsgroupmember method.

**Environment (please complete the following information):**
 - OS:  Win10 64bit
 - PowerShell Version: Windows PowerShell 5.1
 - PSGSuite Version:  2.20.2

Cheers,
Neil

**Comment by scrthq** [comment] 2018-11-28 22:53
Hey @n-searle - This is something I noticed as well when adding Update-GSGroupMember and wasn't able to get around. The scopes in use for either method (Get vs List) are the same, so it's not a scope issue. Going to continue checking this out though! Keeping this open while I dig in

**Comment by scrthq** [comment] 2018-12-24 06:11
Hey @n-searle - From the digging / testing I've done, this looks to be by design (unfortunately). The property is there because the returned object type is the same, but `List` requests using the normal API don't return the `DeliverySettings`/`delivery_settings` property:

`GET` requests include the property as expected:

![image](https://user-images.githubusercontent.com/12724445/50391976-bb500c00-070f-11e9-9b53-b905eff74281.png)


`LIST` requests do not though (and specifying it in `Fields` just throws errors):

![image](https://user-images.githubusercontent.com/12724445/50392029-2a2d6500-0710-11e9-9696-d41b85139866.png)

***

I'm going to close this one down as a vendor side issue. If you find any other ways to approach it, please let me know!

**Closed by scrthq** 2018-12-24 06:11 UTC
Labels: bug, vendor-bug

**Comment by n-searle** [comment] 2018-12-24 17:03
Hiya,

Seems odd they choose to do it this way without adding the option to
request additional properties like you would with active directory
requests, but it is what it is.

Thanks very much for looking into it, have a great Christmas!

Cheers,
Neil

**Comment by scrthq** [comment] 2018-12-24 17:06
@n-searle  Agreed, especially since the object type returned by both from the .NET SDK has the `DeliverySettings` property, seems like a no-brainer to include that property for List requests.

Have a great Christmas as well, Neil!
